#!/usr/bin/env sh

sudo yabai --load-sa

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=display_added   action="yabai --restart-service"
yabai -m signal --add event=display_removed action="yabai --restart-service"
yabai -m signal --add event=display_resized action="yabai --restart-service"
yabai -m signal --add event=display_moved   action="yabai --restart-service"

yabai -m config \
    external_bar                        all:0:0         \
    mouse_follows_focus                 on              \
    focus_follows_mouse                 off             \
    window_zoom_persist                 off             \
    window_placement                    second_child    \
    window_shadow                       off             \
    window_opacity                      off             \
    window_opacity_duration             0.2             \
    active_window_opacity               1.0             \
    normal_window_opacity               0.9             \
    window_animation_duration           0.0             \
    window_animation_easing             0xff9dd274      \
    split_ratio                         0.50            \
    auto_balance                        off             \
    mouse_modifier                      alt             \
    mouse_action1                       move            \
    mouse_action2                       resize          \
    mouse_drop_action                   swap            \
    top_padding                         4               \
    bottom_padding                      4               \
    left_padding                        4               \
    right_padding                       4               \
    window_gap                          4               \

yabai -m config layout bsp

yabai -m rule --add app=".*" sub-layer=normal
yabai -m rule --add app="App Store" manage=off
yabai -m rule --add app="Contexts" manage=off
yabai -m rule --add app="Raycast" manage=off
yabai -m rule --add app="Raspberry" manage=off
yabai -m rule --add app="FirstSpirit ServerManager" manage=off
yabai -m rule --add app="metin2server" manage=off
yabai -m rule --add app="metin2client" manage=off
yabai -m rule --add app="Aktivitätsanzeige" manage=off
yabai -m rule --add app="System­einstellungen" manage=off
yabai -m rule --add app="Karabiner-Elements" manage=off sub-layer=below
yabai -m rule --add app="CitrixEndpointAnalysis" manage=off sub-layer=below
yabai -m rule --add app="Karabiner-EventViewer" manage=off sub-layer=below
yabai -m rule --add title="BloonsTD6" app="BloonsTD6" manage=off
yabai -m rule --add app="Steam Helper" manage=off sub-layer=below
yabai -m rule --add app="Steam" manage=off sub-layer=below
yabai -m rule --add app="Google Chrome" title="^about:blank - " manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="Kopieren" manage=off
yabai -m rule --add app="Ghostty" title="^$" manage=off

yabai -m rule --apply

# yabai -m signal --add event=display_added action="~/.config/yabai/scripts/widescreen-attached.sh"
# yabai -m signal --add event=display_removed action="~/.config/yabai/scripts/widescreen-detached.sh"

# borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0 &
# borders &
